name: biz
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - name: null
    url: null
    item: null
color:
  saturation: 1
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#0E0E0C'
    - '#FFFFFF'
    - '#414139'
    - '#9A876E'
    - '#C6B49B'
  rhythmicContrast: 1
typography_spectrum: 0.61427
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.2615467
