name: biz
favicon: null
layout_spectrum: 0.45161
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#69ad57'
    - '#287c00'
    - '#871007'
    - '#333333'
  brandStrength: 1
  lightness: 1
  saturation: 0.531034
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
