name: biz
favicon: null
layout_spectrum: 0.10817
typography_spectrum: 0.67188
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3A2718'
    - '#DFBEA3'
    - '#6D4A32'
    - '#B3885D'
    - '#B4542F'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.531034
  rhythmicContrast: 0.123558
purpose:
  - name: null
    item: null
    url: null
